spring:
  application:
    name: BananaService
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      write_dates_as_timestamps: false
  cloud:
    bus:
      enabled: false
    discovery:
      enabled: false
    consul:
      enabled: false
      config:
        enabled: false

